// Generated by CoffeeScript 1.7.1
var app, beaconId, setLocation, time;

app = {
  geojsons: {},
  getGeoJSONByLevel: function(level) {
    var geojson;
    geojson = this.geojsons[level];
    geojson.haika = {
      xyLatitude: 35.1550682,
      xyLongitude: 136.9637741
    };
    return geojson;
  },
  loadGeoJSON: function(option) {
    return $.ajax({
      url: "http://lab.calil.jp/haika_store/load.php?major=" + option.major,
      type: 'GET',
      cache: false,
      dataType: 'json',
      error: (function(_this) {
        return function() {
          return option.error && option.error('データが読み込めませんでした');
        };
      })(this),
      success: (function(_this) {
        return function(data) {
          return option.success && option.success(data);
        };
      })(this)
    });
  },
  initGeoJSON: function(major) {
    return this.loadGeoJSON({
      major: major,
      success: (function(_this) {
        return function(data) {
          var geojson, lev, level, levels, _ref;
          _this.geojsons = data.geojson;
          levels = [];
          _ref = data.geojson;
          for (level in _ref) {
            geojson = _ref[level];
            levels.push(level);
          }
          lev = levels[0];
          map.createLevelMenu(levels.reverse());
          return map.loadFloorByLevel(lev);
        };
      })(this),
      error: function(message) {
        return alert(message);
      }
    });
  }
};

app.initGeoJSON(101);

time = 0;

setTimeout(function() {
  return map.createUserLocation(164);
}, time += 1000);

setTimeout(function() {
  return map.createUserLocation(165);
}, time += 1000);

setTimeout(function() {
  return map.createUserLocation(166);
}, time += 1000);

beaconId = 300;

setTimeout(function() {
  map.loadFloorAndchangeShelfColor('3F', 298);
  time = 0;
  return setLocation();
}, time += 1000);

setLocation = function() {
  return setTimeout(function() {
    beaconId += 10;
    map.createUserLocation(beaconId);
    map.changeShelfColor(beaconId - 100);
    if (beaconId < 385) {
      return setLocation();
    }
  }, time += 500);
};

/*
//@ sourceMappingURL=app.map
*/
