// Generated by CoffeeScript 1.7.1
var accuracy, animateMarker, app, delay, deltaLat, deltaLng, i, log, map, marker, moveMarker, position, transition;

log = function(obj) {
  return {
    "try": console.log(obj)
  };
};

map = {
  map: null,
  userLocation: null,
  geosjon: null,
  init: function(divId) {
    return this.map = new google.maps.Map(document.getElementById(divId), {
      disableDefaultUI: true,
      zoom: 19,
      maxZoom: 32,
      center: {
        lat: 0,
        lng: 0
      },
      scaleControl: false
    });
  },
  loadFloorByLevel: function(level) {
    var latlng;
    this.removeUserLocation();
    this.geojson = app.getGeoJSONByLevel(level);
    this.map.data.forEach((function(_this) {
      return function(feature) {
        return _this.map.data.remove(feature);
      };
    })(this));
    latlng = new google.maps.LatLng(this.geojson.haika.xyLatitude, this.geojson.haika.xyLongitude);
    this.map.setCenter(latlng);
    this.map.data.addGeoJson(this.geojson);
    return this.drawGeoJSON();
  },
  drawGeoJSON: function(shelfId) {
    if (shelfId == null) {
      shelfId = 0;
    }
    return this.map.data.setStyle((function(_this) {
      return function(feature) {
        return _this.applyStyle(feature, shelfId);
      };
    })(this));
  },
  changeShelfColor: function(shelfId) {
    return drawGeoJSON(shelfId);
  },
  applyStyle: function(feature, shelfId) {
    var id, type;
    if (shelfId == null) {
      shelfId = 0;
    }
    id = feature.getProperty("id");
    type = feature.getProperty("type");
    if (type === 'floor') {
      return {
        fillColor: "#ffffff",
        fillOpacity: 0.5,
        strokeWeight: 0,
        zIndex: -1
      };
    }
    if (type === 'wall') {
      return {
        fillColor: "#555555",
        fillOpacity: 1,
        strokeWeight: 2,
        strokeColor: "#555555",
        strokeOpacity: 1
      };
    }
    if (type === 'shelf') {
      if (id === shelfId) {
        return {
          fillColor: "#ff0000",
          fillOpacity: 1,
          strokeWeight: 3
        };
      } else {
        return {
          fillColor: "#aaaaff",
          fillOpacity: 1,
          strokeWeight: 2
        };
      }
    }
  },
  loadFloorAndShowHighlight: function(level, shelfId) {
    loadFloorByLevel(level);
    return changeShelfColor(shelfId);
  },
  createUserLocation: function(beaconId) {
    var coordinate, count, feature, lat, lon, markerImage, position, _i, _j, _len, _len1, _ref, _ref1;
    this.removeUserLocation();
    lat = 0;
    lon = 0;
    count = 0;
    _ref = this.geojson.features;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      feature = _ref[_i];
      if (feature.properties.type === 'beacon') {
        if (feature.properties.id === beaconId) {
          count = feature.geometry.coordinates[0].length;
          _ref1 = feature.geometry.coordinates[0];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            coordinate = _ref1[_j];
            lat += coordinate[1];
            lon += coordinate[0];
          }
        }
      }
    }
    if (lat === 0 && lon === 0) {
      return;
    }
    markerImage = new google.maps.MarkerImage('img/marker.png', new google.maps.Size(34, 34), new google.maps.Point(0, 0), new google.maps.Point(17, 17));
    log(lat / count);
    log(lon / count);
    position = new google.maps.LatLng(lat / count, lon / count);
    this.userLocation = new google.maps.Marker({
      position: position,
      map: this.map,
      icon: markerImage
    });
    return this.userLocation.setMap(this.map);
  },
  removeUserLocation: function() {
    if (this.userLocation) {
      this.userLocation.setMap(null);
    }
    return this.userLocation = null;
  },
  animateMarker: function(goLatLng) {
    var counter, delay, drawingNumber, lat, lng, marker, moveMarker, transition;
    drawingNumber = 100;
    delay = 10;
    counter = 0;
    lat = void 0;
    lng = void 0;
    marker = map.userLocation;
    transition = function(result) {
      counter = 0;
      lat = (goLatLng[0] - animateLatLng[0]) / drawingNumber;
      lng = (goLatLng[1] - animateLatLng[1]) / drawingNumber;
      return moveMarker();
    };
    return moveMarker = function() {
      animateLatLng[0] += lat;
      animateLatLng[1] += lng;
      marker.setPosition(new google.maps.LatLng(animateLatLng[0], animateLatLng[1]));
      if (counter !== drawingNumber) {
        counter++;
        return setTimeout(moveMarker, delay);
      }
    };
  },
  createLevelMenu: function(levelArray) {
    var level, _i, _len;
    $('#map-level').empty();
    for (_i = 0, _len = levelArray.length; _i < _len; _i++) {
      level = levelArray[_i];
      $('#map-level').append("<li level=\"" + level + "\">" + level + "</li>");
    }
    return $('#map-level li').mousedown(function() {
      return map.loadFloorByLevel($(this).attr('level'));
    });
  }
};

map.init('map');

app = {
  geojsons: {},
  getGeoJSONByLevel: function(level) {
    var geojson;
    geojson = this.geojsons[level];
    geojson.haika = {
      xyLatitude: 35.1550682,
      xyLongitude: 136.9637741
    };
    return geojson;
  },
  loadGeoJSON: function(option) {
    return $.ajax({
      url: "http://lab.calil.jp/haika_store/load.php?major=" + option.major,
      type: 'GET',
      cache: false,
      dataType: 'json',
      error: (function(_this) {
        return function() {
          return option.error && option.error('データが読み込めませんでした');
        };
      })(this),
      success: (function(_this) {
        return function(data) {
          return option.success && option.success(data);
        };
      })(this)
    });
  },
  initGeoJSON: function(major) {
    return this.loadGeoJSON({
      major: major,
      success: (function(_this) {
        return function(data) {
          var geojson, level, levels, _ref;
          _this.geojsons = data.geojson;
          levels = [];
          _ref = data.geojson;
          for (level in _ref) {
            geojson = _ref[level];
            levels.push(level);
          }
          map.loadFloorByLevel(levels[0]);
          return map.createLevelMenu(levels.reverse());
        };
      })(this),
      error: function(message) {
        return alert(message);
      }
    });
  }
};

app.initGeoJSON(101);

setTimeout(function() {
  return map.createUserLocation(164);
}, 1000);

setTimeout(function() {
  return map.createUserLocation(165);
}, 2000);

setTimeout(function() {
  return map.createUserLocation(166);
}, 3000);

moveMarker = function() {
  var count, lat, lng;
  lat = map.getCenter().lat();
  lng = map.getCenter().lng();
  count = 20;
  return moveMarker = function() {
    lat = lat - 0.000005;
    lng = lng + 0.000005;
    marker.setPosition(new google.maps.LatLng(lat, lng));
    count = count - 1;
    if (count > 0) {
      return setTimeout(moveMarker, 10);
    }
  };
};

position = [35.155001527242796, 136.96389599263];

accuracy = 100;

delay = 10;

i = 0;

deltaLat = void 0;

deltaLng = void 0;

marker = map.userLocation;

transition = function(result) {
  i = 0;
  deltaLat = (result[0] - position[0]) / accuracy;
  deltaLng = (result[1] - position[1]) / accuracy;
  return moveMarker();
};

moveMarker = function() {
  position[0] += deltaLat;
  position[1] += deltaLng;
  marker.setPosition(new google.maps.LatLng(position[0], position[1]));
  if (i !== accuracy) {
    i++;
    return setTimeout(moveMarker, delay);
  }
};

animateMarker = function() {
  var result;
  result = [marker.getPosition().lat(), marker.getPosition().lng()];
  return transition(result);
};

/*
//@ sourceMappingURL=app.map
*/
