// Generated by CoffeeScript 1.7.1
$.extend(map, {
  canvasResize: function() {
    var canvasHeight;
    if (location.hash === '#map_view') {
      canvasHeight = $(window).height() - ($('.header').height() + 1) - ($('.footer').height() + 1);
      $('#map-canvas').height(canvasHeight);
      setTimeout((function(_this) {
        return function() {
          var center;
          center = _this.googleMaps.getCenter();
          google.maps.event.trigger(_this.googleMaps, 'resize');
          return _this.googleMaps.setCenter(center);
        };
      })(this), 50);
    }
  }
});

$(window).on('hashchange orientationchange resize', function() {
  return map.canvasResize();
});

/*
//@ sourceMappingURL=app_map.map
*/
