// Generated by CoffeeScript 1.7.1
var isLocal;

isLocal = function() {
  return location.protocol === 'file:' || location.port !== '';
};

google.maps.event.addDomListener(window, 'load', function() {
  window.map = new google.maps.Map($('#map')[0], {
    zoom: 20,
    center: {
      lat: 35.9619654,
      lng: 136.1863268
    }
  });
  if (isLocal()) {
    return map.data.loadGeoJson('/data/000105.geojson');
  } else {
    return map.data.loadGeoJson('http://lab.calil.jp/haika_store/data/000105.geojson');
  }
});

/*
//@ sourceMappingURL=map.map
*/
