// Generated by CoffeeScript 1.7.1
var featureLayer, map;

map = L.mapbox.map('map', 'examples.map-i86nkdio').setView([35.9620124, 136.18660999999997], 30);

featureLayer = L.mapbox.featureLayer().loadURL('http://lab.calil.jp/haika_store/data/000105.geojson').addTo(map);

/*
//@ sourceMappingURL=mapbox.map
*/
